#! /usr/bin/env bash
echo "== create bucket"

# Exit immediately if any command returns a non-zero status
set -e

# Check for bucket name
if [ -z "$1" ]; then
    echo "No bucket name provided."
    echo "./create-bucket <bucket-name>"
    exit 1
fi

BUCKET_NAME=$1

# https://docs.aws.amazon.com/cli/latest/reference/s3api/create-bucket.html
aws s3api create-bucket \
--bucket $BUCKET_NAME  \
--create-bucket-configuration "LocationConstraint=eu-west-1" \
--query Location \
--output text