#! /usr/bin/env bash
echo "== delete bucket"

# Check if 1 argument is provided
if [ -z "$1" ]; then
    echo "No bucket name provided."
    echo "./delete-bucket <bucket-name>"
    exit 1
fi

# https://docs.aws.amazon.com/cli/latest/reference/s3api/delete-bucket.html
aws s3api delete-bucket \
--bucket $1 \
