#! /usr/bin/env bash
echo "== get newest bucket"

# Exit immediately if any command returns a non-zero status
set -e

# https://docs.aws.amazon.com/cli/latest/reference/s3api/list-buckets.html
aws s3api list-buckets | jq -r '.Buckets | sort_by(.CreationDate) | reverse | .[0] | .Name'
