#! /usr/bin/env bash
echo "== list newest buckets"

# Exit immediately if any command returns a non-zero status
set -e

# https://docs.aws.amazon.com/cli/latest/reference/s3api/list-buckets.html
aws s3api list-buckets | jq -r '.Buckets | sort_by(.CreationDate) | reverse | .[0:5] | .[] | .Name'
echo "..."