#! /usr/bin/env bash
echo "== put object"

# Exit immediately if any command returns a non-zero status
set -e

# Check for bucket name
if [ -z "$1" ] || [ -z "$2" ]; then
    echo "Usage:"
    echo "./put-object <bucket-name> <filename>"
    exit 1
fi 

BUCKET_NAME=$1
FILENAME=$2

OBJECT_JEY=$(basename "$FILENAME")

# https://docs.aws.amazon.com/cli/latest/reference/s3api/put-object.html
aws s3api put-object \
--bucket $BUCKET_NAME \
--body $FILENAME \
--key $OBJECT_JEY