#! /usr/bin/env bash
echo "== sync"

# Exit immediately if any command returns a non-zero status
set -e

# Check for bucket name
if [ -z "$1" ] || [ -z "$2" ]; then
    echo "Usage:"
    echo "./sync <bucket-name> <filename-prefix>"
    exit 1
fi 

BUCKET_NAME=$1
FILENAME_PREFIX=$2

# location to store files
OUTPUT_DIR="/tmp/s3-bash-scripts"

# remove the folder if it already exits
rm -r $OUTPUT_DIR

# create output folder
mkdir -p $OUTPUT_DIR

# random number to determine the number of files to create
NUM_FILES=$((RANDOM % 6 + 5))

for ((i=1; i<=$NUM_FILES; i++)) do 
    FILENAME="$OUTPUT_DIR/${FILENAME_PREFIX}_$i.txt"

    # generate random data and write it to the file
    dd if=/dev/urandom of="$FILENAME" bs=1024 count=$((RANDOM % 1024+ 1)) 2>/dev/null
done

tree $OUTPUT_DIR

# https://docs.aws.amazon.com/cli/latest/reference/s3/sync.html
aws s3 sync $OUTPUT_DIR s3://$BUCKET_NAME/files